language: node_js
node_js:
- "11.3.0"
dist: xenial
sudo: false
addons:
  ssh_known_hosts:
  - chws.ca
before_install:
- openssl aes-256-cbc -K $encrypted_ede01122f305_key -iv $encrypted_ede01122f305_iv
  -in .travis/deploy_rsa.enc -out .travis/deploy_rsa -d
- eval "$(ssh-agent -s)"
- cp .travis/deploy_rsa ~/.ssh/deploy_rsa
- chmod 600 ~/.ssh/deploy_rsa
- ssh-add ~/.ssh/deploy_rsa
deploy:
- provider: script
  skip_cleanup: true
  script: ".travis/deploy.sh"
  on:
    branch: master
