# Start from the node base image
FROM node:latest

# Set the working directory in the Docker container
WORKDIR /app

# Copy the package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your app's source code
COPY . .

# build the static website section
RUN npm run build

# Expose port 3000 to the outside world
EXPOSE 3000

# Start the app
CMD ["npm", "start"]

# then you can access it via:
# http://localhost:3000/resume/

# note: the normal way for development is just to run `npm start` locally, it will go on port 3000 that way too but be live updating dev server
#       not just node js serving a statically built site which is what running this image will do.