export const resumeData = {
	"personal_info":{
		"name":"Chris A. Hagglund",
		"email":"chris@chws.ca",
		"phone":"250-532-9694",
		"location":"1635 Cook St, Victoria BC",
		"profile":"Over 15 years of industry experience building and maintaining backend systems. A passion for delivering results and solving the problems that were thought to be too difficult.",
	},
	"key_skills":[
		"Developing backend solutions and integrations, building microservices, supporting web apps",
		"Coding in Golang, Python, Javascript/Node.js, Perl, PHP",
		"Handling data with MySQL, Postgres, Redis, RDS, Redshift, RabbitMQ, and more",
		"Using tools like Linux, Nginx, REST, React, HTML5, SCSS [Coming soon: Docker, Travis], and more",
	],
	"work_history"	: [{
		"company":"CHWS",
		"companydesc":"Software Development Consultancy",
		"location":"Victoria",
		"jobtitle":"Senior Software Developer",
		"daterange": "2010 - Present",
		"projects":[{
			"desc":"Web integration of bitcoin lightning network payments for earmarked charitable donations. Generate invoice and present payment request to user, plus show invoice paid status when paid.",
			"dates":"May 2019",
			"sortdate":"2019-05-01",
			"github":"https://github.com/BladeMcCool/goober",
			"tech":"Golang, Nginx, JavaScript, HTML5, LND, Bitcoind",
			"location":"Victoria",
			"jobtitle":"Open Source Developer",
		},{
			"desc":"Twitter bot for signup, email+sms validate, and replay of conversations, for a client in the SEO Business. Tweet search code to pull out hundreds of thousands of tweets per target profile and store in database for further use. Webmail account checking code to confirm thousands accounts as working and to log them in with cookies",
			"dates":"Nov 2018 - Jan 2019",
			"sortdate":"2019-01-01",
			"tech":"Node.js, Puppeteer, MySQL, Redis",
			"location":"Remote",
		},{
			"desc":"SEO link network building infrastructure targeting status.net, pligg and wiki sites, with extensive use of captcha bypass services. SEO business administration/workflow software to direct and verify employee article writing tasks.",
			"dates":"2010 - 2012",
			"sortdate":"2012-01-01",
			"tech":"Perl, Python, MySQL",
			"location":"Remote",
		},{
			"desc":"Captcha solving game, where players were rewarded with XP and levelup animations for correctly completing captchas, in order to enable a bot posting on 4chan's /b/ board",
			"dates":"Fall 2010",
			"sortdate":"2010-10-01",
			"tech":"Perl, HTML, Javascript",
			"location":"Victoria",
		},{
			"desc":"Telephone based Bitcoin IVR custodial wallet system using VoiP phone number. Customer could phone in and check balance, send and receive payments. Live payment notification possible.",
			"dates":"Early 2010",
			"sortdate":"2010-03-01",
			"tech":"Perl, Asterisk, Bitcoind",
			"github":"https://github.com/BladeMcCool/BitcoinIVR",
			"location":"Victoria",
			"jobtitle":"Open Source Developer",
			"pageBreakBefore":true,
		}]
	},{
		"company":"Go2mobi",
		"companydesc":"Mobile Advertising Self-Serve DSP",
		"location":"Victoria",
		"jobtitle":"Senior Software Developer",
		"desc":"Built and maintained mobile advertising Real Time Bidder in Python, later transitioned to Golang. Handled 500,000 queries per second on a cluster of 15 servers. Also developed processes for ETL and reporting the hundreds of millions of records per day generated by the bidder. Rearchitected existing click tracking system for better performance.",
		"tech":"Golang, Node.js, Python, AWS, RabbitMQ, Redis, MySQL+Postgres",
		"daterange": "Nov 2012 - Feb 2017",
		"sortdate":"2017-02-01",
	},{
		"company":"Shrinking Planet Communications",
		"companydesc":"Content Management Systems and Web Application Development",
		"location":"Toronto, ON",
		"jobtitle":"Full Stack Developer",
		"daterange": "2002 - 2009",
		"sortdate":"2009-02-01",
		"desc":"Maintained existing CMS and Email broadcast systems written in Perl and being used by hundreds of clients. Improved performance of infrastructure through employing enhanced server efficiency tools like mod_perl under Apache. Built a web application tool kit which included a robust custom SQL abstraction ORM. Integrated with credit card processing providers like Moneris.",
		"tech":"Perl, Apache, MySQL, Javascript, CSS, HTML Templating"
	},{
		"company":"Glacier Digital",
		"companydesc":"Enterprise Application Development and Content Management Systems",
		"location":"Burlington, ON",
		"jobtitle":"Senior Software Developer",
		"daterange": "1999 - 2011",
		"projects":[{
			"desc":"Ported a hotel franchise invoicing system from Cold Fusion to PHP due to new server requirements. Successfully completed with identical functionality to original CFM code, and made some security improvements to prevent SQL injection vulnerabilities.",
			"dates":"2011",
			"tech":"CFM, PHP, MySQL",
			"location":"Remote",
			"sortdate":"2011-06-01",
		},{
			"desc":"Improved the machine-generated output of some y2k-era web tools to add additional server side (vbscript asp) and client side functionality related to a content management system that was being developed, as well as database table setup for localisation with different languages.",
			"dates":"1999",
			"sortdate":"1999-06-01",
			"tech":"VBScript, HTML",
			"location":"Remote",
		}]
	},{
		"company":"SunLife Financial",
		"companydesc":"Enterprise Application Development and Content Management Systems",
		"location":"Toronto, ON",
		"jobtitle":"Intern - Internet Technologies Group",
		"daterange": "Summer 2001",		
		"sortdate":"2001-06-01",
		"desc":"Diagrammed portions of the network infrastructure in the SunLife network using Visio 2000. Performed routine server maintenance (log rotation, disk space checking) of a small set of Solaris servers with the assistance of custom made scripts. Wrote a perl script to catalog the various internal web-services that were available in the intranet and present the results in a web interface.",
		"tech":"Perl, Oracle, Bash, Unix, Visio 2000"
	}],
	"education":[
		"Humber College (Toronto, 3 year Computer/Programmer/Analyst Diploma, May 2002)",
		"CompTIA A+ (Computer Service Technician Certification, Toronto, 2000)",
		"White Oaks Secondary School (Oakville, OSSD, June 1999)",
	],
	"hobbies":[
		"Hiking",
		"Cooking",
		"Learning",
		"Bitcoin",
	]
}