name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
#
#  build:
#
#    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      packages: write
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#
#      - name: Log in to GitHub Docker Registry
#        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
#
#      - name: Build and push Docker image
#        run: |
#          docker build .  -t ghcr.io/blademccool/resume:${{ github.sha }}
#          docker push ghcr.io/blademccool/resume:${{ github.sha }}
#
#      # only tag master when we merged or pushed directly.
#      - name: Tag latest Docker image
#        if: github.event_name == 'push'
#        run: |
#          docker tag ghcr.io/blademccool/resume:${{ github.sha }} ghcr.io/blademccool/resume:${{ github.ref_name }}
#          docker push ghcr.io/blademccool/resume:${{ github.ref_name }}

# legacy methodology was to just trigger the pipeline and let it figure out the ref but as it was correctly pointed out to me, this methodology precludes reproducible builds. henceforth we will commit the ref of the resume to use right into the master branch of the website (see down below)
#        # trigger pipeline in website repo
#        # this requires a PAT, and it does not allow the classic style that allow no expiry.
#        # WEBSITE_PIPELINE_PAT (believed to expire 2025-03-18) is a fine-grained one targeting the chws.ca repo which includes "Read and Write" for both Actions and Contents (it didnt work without Contents, havent verified if Actions is actually even needed)
#      - name: Deploy via Website repo
#        if: github.event_name == 'push' # only after pushing directly or merging into master tho
#        run: >
#          curl -sS -H "Accept: application/vnd.github.everest-preview+json" \
#            -H "Authorization: token ${{ secrets.WEBSITE_PIPELINE_PAT }}" \
#            --request POST \
#            --data '{"event_type": "subcomponent_updated", "client_payload": { "component":"resume", "sha":"${{ github.sha }}"}}"}}' \
#            https://api.github.com/repos/BladeMcCool/chws.ca/dispatches

  update_ref:
    if: github.event_name == 'push' # only after pushing directly or merging into master tho

    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: BladeMcCool/chws.ca
          ref: 'master'
          token:  ${{ secrets.WEBSITE_PIPELINE_PAT }}

      - name: Update Resume Ref in deps.env
        run: |
          sed -i "s/^RESUME_REF=.*/RESUME_REF=${{ github.sha }}/" deps.env
          git config --global user.name 'Resume Updater Bot'
          git config --global user.email 'robots@chws.ca'
          git add deps.env
          git commit -m "Update RESUME_REF to ${{ github.sha }}"
          git push          
